main: me.deejayarroba.craftheads.Main
version: 1.4
name: CraftHeads
author: DeejayArroba
commands:
   craftheads:
      usage: Syntax error! Use /<command>
      permission: craftheads.use
      description: Open the CraftHeads menu.
permissions:
   craftheads.*:
      description: Gives access to all of CraftHeads features
      children:
         craftheads.use: true
         craftheads.updater: true
   craftheads.use:
      description: Gives access to the CraftHeads menu
      default: op
   craftheads.updater:
      description: Gives access to CraftHeads updates
      default: op