# This enables the check for updates.
# If this is set to true and "auto-update" is set to false, you will get notifications about updates.
# If don't want to check for updates, set this to false.
update-check: true

# This enables the plugin to download a new version if an update is detected.
# For this to work you have to set "update-check" to true.
# If you don't want to download updates automatically, set this to false.
auto-update: false

# This enables metrics.
# If you don't want metrics enabled set this to false.
metrics: true