# CraftHeads Configuration File
# For documentation about the configuration file check the following website:
# http://dev.bukkit.org/bukkit-plugins/craftheads/pages/default-configuration-file/
update-check: true
auto-update: true
metrics: true
economy: false
default-price: 100
player-own-head-price: 100
player-other-head-price: 100
reset-categories: true